### ISSUE TITLE
Meeting Host Prefrences

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#4]
As a Meeting Host
I want to be able to specify the hours I'm available to host a meeting and the calendars that neverl8 should look at to see if there are meeting conflicts
So That individual requesting a meeting can see what hours I'm available.

**Comment by drewfugate** [comment]
If we have all our separate repository tests in their own files but under the repository_test package, the test will enter the repository_test.go file first since it contains TestMain. This allows a singular test starting point so our test files need virtually no "boiler plate" code to start/teardown the DB each time. This may be obvious, but I thought it was pretty cool.

![Image](https://github.com/rise8-us/neverl8/assets/102103212/bd2d39f3-04fc-4bab-b8e4-b6fd33ad7a11)



![Image](https://github.com/rise8-us/neverl8/assets/102103212/0d368385-cc4e-4a6a-87e7-fcf3a128508a)
